import { Inter } from "next/font/google";
import { Gluestackproviders } from "../context/Gluestackproviders";
import StyledJsxRegistry from "../context/registry"
import Usercontextcmp from "../context/userContext"
import { Reactqueryprovider } from "../context/reactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="gs">
      <body className={inter.className}>
        <Usercontextcmp>
          <Reactqueryprovider>
            <Gluestackproviders>
              <StyledJsxRegistry>{children}</StyledJsxRegistry>
            </Gluestackproviders>
          </Reactqueryprovider>
        </Usercontextcmp>
      </body>
    </html>
  );
}
